<h1>Editar Lista de Alunos</h1>
<hr>
<form class="col-4 offset-4 mt-4" action="#" method="POST">
    <input type="hidden" class="form-control" name="id" value="<?php echo $dados["id"] ?>">
    <div class="col">
        <label class="form-label">Nome</label>
        <input type="text" class="form-control" name="nome" value="<?php echo $_POST["nome"] ?? $dados["nome"] ?>">
    </div>
    <div class="col">
        <label class="form-label">Email</label>
        <input type="text" class="form-control" name="email" value="<?php echo $_POST["email"] ?? $dados["email"] ?>">
    </div>
    <div class="col">
        <label class="form-label">Contato</label>
        <input type="text" class="form-control" name="contato" value="<?php echo $_POST["contato"] ?? $dados["contato"]; ?>" placeholder="(  )     -    ">
    </div>
    <div class="col">
        <label class="form-label">Endereço</label>
        <input type="text" class="form-control" name="endereco" value="<?php echo $_POST["endereco"] ?? $dados["endereco"]; ?>" placeholder="Av, rua">
    </div>
    <div class="col">
        <label class="form-label">Cidade</label>
        <input type="text" class="form-control" name="cidade" value="<?php echo $_POST["cidade"] ?? $dados["cidade"] ?>" placeholder="Cidade">
    </div>
    <div class="col mb-3">
        <label class="form-label">Matricula</label>
        <input type="text" class="form-control" name="matricula" value="<?php echo $_POST["matricula"] ?? $dados["matricula"] ?>" placeholder="Matricula">
    </div>
    <div class="col">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</form>