<!-- <h1 class="text-center">Inicio</h1> -->

        <div class="col-4 offset-4 mt-5 h-75 ">
            <div class="card card-body bg-dark text-white m-2">
                <div class="h3 text-center">LOGIN</div>
                <hr>
                <form>
                    <input class="form-control form-control-lg mb-3" type="email" placeholder="Email">

                    <input class="form-control form-control-lg mb-3" type="senha" placeholder="Senha">

                    <div class="d-grid">
                        <button class="btn btn-lg btn-primary btn-md">
                            Entrar</button>
                        <!--Posso deixar o Button fora do form-->
                    </div>
                </form>
            </div>
            <!-- <div class="nav justify-content-center"><a href="esqueceusenha.html" class="btn btn-outline-dark">Esqueceu a senha?</a></div> -->
        </div>
        <!-- <div class="col bg-danger">Direita</div> -->

<hr>
<!-- <div class="col">
    <a href="./listar"><button type="button" class="btn btn-primary">Lista de Alunos</button></a>
</div> -->


