<hr>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <h3 class="text-center mt-4">Cadastre Novos Aluno</h3>
    <form class="col-4 offset-4 mt-4" action="#" method="POST">
    <div class="col">
        <label class="form-label">Nome</label>
        <input  type="text" class="form-control" name="nome" value="<?php echo $_POST['nome'] ?? ''?>">
    </div>
    <div class="col">
        <label class="form-label">Email</label>
        <input  type="text" class="form-control" name="email" value="<?php echo $_POST['email'] ?? ''?>">
    </div>
    <div class="col">
        <label class="form-label">Contato</label>
        <input  type="text" class="form-control" name="contato" placeholder="(  )     -    " value="<?php echo $_POST['contato'] ?? ''?>">
    </div>
    <div class="col">
        <label class="form-label">Endereço</label>
        <input  type="text" class="form-control" name="endereco" placeholder="Av, rua" value="<?php echo $_POST['endereco'] ?? ''?>">
    </div>
    <div class="col">
        <label  class="form-label">Cidade</label>
        <input  type="text" class="form-control" name="cidade" placeholder="Cidade" value="<?php echo $_POST['cidade'] ?? ''?>">
    </div>
    <div class="col mb-3">
        <label  class="form-label">Matricula</label>
        <input  type="text" class="form-control" name="matricula" placeholder="Matricula" value="<?php echo $_POST['matricula'] ?? ''?>">
    </div>
    <div class="col">
        <button type="submit" class="btn btn-primary">Enviar</button>
        <!-- <a href="./listar"><button type="button" class="btn btn-primary">Lista de Alunos</button></a> -->
        
    </div>
    </form>
</body>
</html>
<hr>